### ISSUE TITLE
Config File and Order of Import

### ISSUE THREAD

**Issue by Btibert3** [neo4j-field/pyingest#5]
Is it possible to specify the order of the (CSV) files for import?  I have them in a specific order within the `files` section, but they were not imported in the same order.  Simply, of the files I specified, the ingestion process started with the 3rd file specified, went to the 4th, etc.

Perhaps there is a config that I am not leveraging, as I would expected to set the order of operations just as I could in a script using `py2neo`.  Overall I really like this approach, but in a way where I can control the order of operations.

**Comment by mholford-neo** [comment]
It's supposed to process the files in order unless the skip_file property is set to true.
Can you share the config and program output?

**Comment by Btibert3** [comment]
I am a dummy, I misread the output when I had an issue in the cypher for one of my imports.  Closing this.

**Comment by mholford-neo** [comment]
No worries!
